// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwrwwctcgpjqlsezacmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cnd3Y3RjZ3BqcWxzZXphY21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDgyMjAsImV4cCI6MjA1MDk4NDIyMH0.lNUcM7_NCUd8kGeWz5bUk6fybKLAGQfBItMOq57NT1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);